### ISSUE TITLE
Błąd importowania bazy

### ISSUE THREAD

**Issue by szogun1910** [x-Scripts/TS3AB-Panel#1]
Hej, mam malutki problem aby zaimportować bazę danych.

`--
-- Zrzut danych tabeli `xDashBotRights`
--

INSERT INTO `xDashBotRights` (`id`, `clientPanel`, `clientFiles`, `rightsCmd`, `groups`) VALUES
('default', '[]', '[]', '[]')

MySQL zwrócił komunikat: Dokumentacja
#1136 - Column count doesn't match value count at row 1`

**Comment by x-Scripts** [comment]
Zamień INSERT INTO xDashBotRights (id, clientPanel, clientFiles, rightsCmd, groups) VALUES
('default', '[]', '[]', '[]') na to INSERT INTO xDashBotRights (id, clientPanel, clientFiles, rightsCmd, groups) VALUES
('default', '[]', '[]', '[]','[]')

**Comment by szogun1910** [comment]
Ogarnięte już wcześniej lecz pozostawione niech zostanie dla innych w razie czego :)
